default_language_version:
  python: python3.7
default_stages: [commit]
exclude: (others/,)

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort
        language: python
        types: [python]

      - id: black
        name: black
        entry: poetry run black
        language: python
        types: [python]

      - id: flake8
        name: flake8
        entry: poetry run flake8
        language: python
        types: [python]

      - id: mypy
        name: mypy
        entry: poetry run mypy .
        language: python
        types: [python]
        pass_filenames: false

